configuration: Release

version: 0.0.1.{build}

before_build:
- cmd: nuget restore WarApiCSharpDriver.sln

test:
  assemblies:
  - WarApi.UnitTests.dll
  - WarApi.CodeGenerator.IntegrationTests
  - WarApi.WoTCSharpDriver.IntegrationTests

notifications:
- provider: Email
  to:
  - abramov.dmitry92@gmail.com
  subject: 'WarApiCSharpDriver. Build status: {{status}}'
  message: >-
    <div style="font-family:'Segoe UI',Arial,Sans-Serif;font-size:10pt;">
        {{#passed}}
        <h1 style="font-size: 150%;font-weight:normal; color:#078DC7;"><a href="{{buildUrl}}" style="color:#078DC7;">Build {{projectName}} {{buildVersion}} completed</a></h1>{{/passed}}
        {{#failed}}
        <h1 style="font-size: 150%;font-weight:normal; color:#ff3228;"><a href="{{buildUrl}}" style="color:#ff3228;">Build {{projectName}} {{buildVersion}} failed</a></h1>{{/failed}}
        <p style="color: #888;">
            Commit <a href="{{commitUrl}}">{{commitId}}</a> by <a href="mailto:{{commitAuthorEmail}}">{{commitAuthor}}</a> on {{commitDate}}:
            <br />
            <span style="font-size: 110%;color:#222;">{{commitMessage}}</span>
        </p>
    </div>
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false